name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run gulp
    - run: AwsAccessKeyID=${{secrets.AwsAccessKeyID}} AwsSecretAccessKey=${{secrets.AwsSecretAccessKey}} npm run deploy
      env:
        CI: true
